# Data types in Python
Nearly everything in Python is an *object*.  For example, a function like $f: x \mapsto x^2$ would be considered an object in Python. Maybe that's surprising to you.  Less surprisingly, an integer like $x = 3$ and a float like $y = 3.141$, and a list like $a = [3,1,4,1]$ are all considered objects. From the official Python [documentation](https://docs.python.org/3/reference/datamodel.html):
> Every object has an **identity**, a type and a value. An object’s identity never changes once it has been created; you may think of it as the object’s address in memory...
>
> An object’s **type** determines the operations that the object supports (e.g., “does it have a length?”) and also defines the possible values for objects of that type. The type() function returns an object’s type (which is an object itself). Like its identity, an object’s type is also unchangeable.
>
> The **value** of some objects can change. Objects whose value can change are said to be mutable; objects whose value is unchangeable once they are created are called immutable... An object’s mutability is determined by its type; for instance, numbers, strings and tuples are immutable, while dictionaries and lists are mutable.

These three properties in the context of Math 10:
* *Identity*: The least important for us.  I learned about this property relatively recently, and I don't find myself thinking about it very often.
* *Value*: Extremely important, but it's so natural that you already understand it, even if you don't realize it.
* *Type*: Extremely important.  The focus of this notebook.  Some examples of types are functions, integers, floats, and lists.

## A few examples of types in Python
You can find the type of an object by using the built-in Python function "type".

In [3]:
def f(x):
    return x**2

In [4]:
type(f)

function

In [5]:
x = 3

In [6]:
type(x)

int

In [7]:
y = 3.141

In [8]:
type(y)

float

In [9]:
a = [3,1,4,1]

In [10]:
type(a)

list

## Why are types important?
### Recognizing new types
Related biblical quote:
> What has been will be again,<br>
> what has been done will be done again;<br>
> there is nothing new under the sun.

When you start working with a new library in Python, there is a good chance it will use its own types of objects.  It can be intimidating at first, but the more experienced you become with Python, the more these objects will start to look familiar.  For example, if you are comfortable with Python dictionaries, and then start reading about the Series type in pandas, you will see many similar features.


In [56]:
import pandas as pd

In [57]:
sample_dict = {"a":10, "b":20, "c": -5, "chris":20}

In [58]:
type(sample_dict)

dict

In [59]:
sample_Series = pd.Series(sample_dict)

In [60]:
sample_Series

a        10
b        20
c        -5
chris    20
dtype: int64

In [61]:
type(sample_Series)

pandas.core.series.Series

In [62]:
sample_dict["c"]

-5

In [63]:
sample_Series["c"]

-5

In [68]:
sample_dict["e"]

KeyError: 'e'

In [69]:
sample_Series["e"]

KeyError: 'e'

In [66]:
sample_dict.get("e",5)

5

In [67]:
sample_Series.get("e",5)

5

### Functions
When trying to understand a Python function, an important step is understanding what type of objects it takes as inputs and returns as outputs.
<img src="images/dropna.png" width = 800/>
Another example:
<img src="images/np_choice.png" width = 800>

## Aside on identity and value

In [24]:
a = [3,1,4,1]

In [25]:
b = [3,1,4,1]

In [26]:
a == b

True

In [27]:
a is b

False

In [28]:
help(id)

Help on built-in function id in module builtins:

id(obj, /)
    Return the identity of an object.
    
    This is guaranteed to be unique among simultaneously existing objects.
    (CPython uses the object's memory address.)



In [29]:
id(a)

140223312564032

In [30]:
id(b)

140222632193600

(I originally tried to do the above example using integers, but to my surprise it said the identities of the integers were the same.  It seemed more likely to work for lists because lists are mutable.)

Here is an example of changing an object's value.  This example also shows that you can have different types of objects in a list.

In [31]:
c = [3,1,4,1]

In [39]:
c.append(f)

In [40]:
c.append(17)

In [41]:
c.append(a)

In [42]:
c

[3,
 1,
 4,
 1,
 <function __main__.f(x)>,
 [3, 1, 4, 1],
 17,
 <function __main__.f(x)>,
 17,
 [3, 1, 4, 1]]

In [2]:
import numpy as np

In [3]:
rng = np.random.default_rng()

In [12]:
A = np.zeros((4,10))

In [6]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
A[2,[3,1,5]] = 1

In [8]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
n = rng.choice(range(10),4)
n

array([8, 1, 1, 1])

In [13]:
A[2,n] = 1

In [14]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
n

array([8, 1, 1, 1])

In [16]:
for v in n:
    print(v)

8
1
1
1


In [17]:
for v in n:
    print(v)

8
1
1
1


In [18]:
A[2,n] = 1

In [19]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])