In [1]:
import numpy as np

In [2]:
mask = [[True,True,False],[True,True,False],[False,False,False]]

In [5]:
display(mask)

[[True, True, False], [True, True, False], [False, False, False]]

In [8]:
np.where(mask,3,2)

array([[3, 3, 2],
       [3, 3, 2],
       [2, 2, 2]])

In [16]:
A = np.where(mask,[5,1,4],[3,2,5])

In [18]:
A

array([[5, 1, 5],
       [5, 1, 5],
       [3, 2, 5]])

In [28]:
A[np.asarray(mask)] = 6

In [29]:
A

array([[  6,   6, 100],
       [  6,   6, 100],
       [  3,   2, 100]])

In [23]:
A[A > 3] = 100

In [25]:
A > 3

array([[ True, False,  True],
       [ True, False,  True],
       [False, False,  True]])

In [26]:
mask

[[True, True, False], [True, True, False], [False, False, False]]

In [34]:
A[0][[True,False,True]] = 1

In [35]:
A

array([[  1,   6,   1],
       [  6,   6, 100],
       [  3,   2, 100]])